# syntax=docker/dockerfile:1

# Use and Ubuntu base image
FROM ubuntu:latest

# Update and install required packages
RUN apt-get update && \
	apt-get install -y lsb-core

# Set the working directory


# Copy your application files


# Start your application


